# Generated by Django 6.0.5 on 2026-06-10 18:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('crime_type', models.CharField(choices=[('harassment', 'Harassment'), ('theft', 'Theft'), ('assault', 'Assault'), ('robbery', 'Robbery'), ('stalking', 'Stalking'), ('vandalism', 'Vandalism'), ('other', 'Other')], max_length=20)),
                ('severity', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=2)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('date_occurred', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_reported'],
            },
        ),
        migrations.CreateModel(
            name='SafeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('zone_type', models.CharField(choices=[('police', 'Police Station'), ('hospital', 'Hospital'), ('pharmacy', 'Pharmacy'), ('fire_station', 'Fire Station'), ('public_space', 'Public Space'), ('shopping', 'Shopping Area'), ('transit', 'Transit Station'), ('community_center', 'Community Center'), ('other', 'Other')], max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius', models.FloatField(default=200, help_text='Safety radius in meters')),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('operating_hours', models.CharField(blank=True, default='24/7', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AreaSafetyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('crime_score', models.FloatField(default=50)),
                ('lighting_score', models.FloatField(default=50)),
                ('crowd_score', models.FloatField(default=50)),
                ('overall_score', models.FloatField(default=50)),
                ('time_period', models.CharField(choices=[('day', 'Day'), ('night', 'Night')], max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('latitude', 'longitude', 'time_period')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_type', models.CharField(choices=[('audio', 'Audio Recording'), ('video', 'Video Recording'), ('photo', 'Photo Evidence')], max_length=10)),
                ('status', models.CharField(choices=[('recording', 'Recording'), ('saved', 'Saved'), ('uploaded', 'Uploaded to Cloud')], default='recording', max_length=15)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('file_size_kb', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_emergency', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_recordings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FakeCallProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_name', models.CharField(default='Ammi', max_length=100)),
                ('caller_number', models.CharField(blank=True, default='+92 300 0000000', max_length=20)),
                ('caller_photo', models.CharField(choices=[('female1', 'Woman 1'), ('male1', 'Man 1'), ('female2', 'Woman 2'), ('male2', 'Man 2')], default='female1', max_length=10)),
                ('delay_seconds', models.IntegerField(default=5, help_text='Delay before call rings')),
                ('ringtone', models.CharField(choices=[('default', 'Default Ring'), ('vibrate', 'Vibrate Only'), ('loud', 'Loud Ring'), ('silent', 'Silent (Screen Only)')], default='default', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fake_call_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_lat', models.FloatField()),
                ('source_lng', models.FloatField()),
                ('dest_lat', models.FloatField()),
                ('dest_lng', models.FloatField()),
                ('source_name', models.CharField(blank=True, max_length=300)),
                ('dest_name', models.CharField(blank=True, max_length=300)),
                ('current_lat', models.FloatField(blank=True, null=True)),
                ('current_lng', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('sos', 'SOS Triggered'), ('unconfirmed', 'Arrival Unconfirmed'), ('cancelled', 'Cancelled')], default='planned', max_length=15)),
                ('safety_score', models.FloatField(default=0)),
                ('route_data', models.JSONField(default=dict)),
                ('eta_minutes', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkin_interval', models.IntegerField(default=0, help_text='Check-in interval in minutes (0=disabled)')),
                ('last_checkin', models.DateTimeField(blank=True, null=True)),
                ('next_checkin_due', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('sos', 'SOS Emergency'), ('checkin_missed', 'Missed Check-In'), ('deviation', 'Route Deviation'), ('arrival_unconfirmed', 'Arrival Not Confirmed')], default='sos', max_length=25)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('false_alarm', 'False Alarm')], default='active', max_length=15)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_alerts', to=settings.AUTH_USER_MODEL)),
                ('journey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='core.journey')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArrivalConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed Safe'), ('unconfirmed', 'Not Confirmed'), ('alert_sent', 'Alert Sent to Contacts')], default='pending', max_length=15)),
                ('confirmation_due_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('grace_period_minutes', models.IntegerField(default=5)),
                ('alert_sent', models.BooleanField(default=False)),
                ('journey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_confirmation', to='core.journey')),
            ],
        ),
        migrations.CreateModel(
            name='JourneyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_safe', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='core.journey')),
            ],
            options={
                'ordering': ['-checked_in_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_updates', to='core.journey')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RouteAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_lat', models.FloatField()),
                ('source_lng', models.FloatField()),
                ('dest_lat', models.FloatField()),
                ('dest_lng', models.FloatField()),
                ('source_name', models.CharField(blank=True, max_length=300)),
                ('dest_name', models.CharField(blank=True, max_length=300)),
                ('travel_time', models.CharField(choices=[('day', 'Day'), ('night', 'Night')], max_length=10)),
                ('safety_score', models.FloatField(default=0)),
                ('route_type', models.CharField(default='safest', max_length=20)),
                ('analysis_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteDeviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('distance_from_route', models.FloatField(help_text='Distance from expected route in meters')),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('user_confirmed_safe', 'User Confirmed Safe'), ('alert_sent', 'Alert Sent'), ('resolved', 'Resolved')], default='detected', max_length=25)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('user_response', models.CharField(blank=True, max_length=200)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviations', to='core.journey')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='SafeNetworkAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('message', models.CharField(default='I need help nearby!', max_length=300)),
                ('radius_meters', models.IntegerField(default=1000)),
                ('members_notified', models.IntegerField(default=0)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_help_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SafeNetworkMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline')], default='offline', max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('bio', models.CharField(blank=True, max_length=200)),
                ('helped_count', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safe_network_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('harassment', 'Harassment'), ('stalking', 'Stalking'), ('unsafe_area', 'Unsafe Area'), ('broken_light', 'Broken Streetlight'), ('suspicious', 'Suspicious Activity'), ('unsafe_road', 'Unsafe Road'), ('safe_spot', 'Safe Spot'), ('other', 'Other')], max_length=20)),
                ('severity', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=2)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('upvotes', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_reported'],
            },
        ),
        migrations.CreateModel(
            name='TransportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('rickshaw', 'Auto Rickshaw'), ('taxi', 'Taxi/Cab'), ('careem', 'Careem'), ('indriver', 'InDriver'), ('uber', 'Uber'), ('bus', 'Public Bus'), ('private', 'Private Vehicle'), ('other', 'Other')], max_length=20)),
                ('plate_number', models.CharField(max_length=20)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('driver_phone', models.CharField(blank=True, max_length=20)),
                ('vehicle_color', models.CharField(blank=True, max_length=30)),
                ('vehicle_description', models.CharField(blank=True, max_length=200)),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('pickup_address', models.CharField(blank=True, max_length=300)),
                ('destination_address', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('active', 'Active Ride'), ('completed', 'Completed Safely'), ('alert', 'Alert Triggered')], default='active', max_length=15)),
                ('expected_duration_minutes', models.IntegerField(default=30)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('shared_with_contacts', models.BooleanField(default=True)),
                ('journey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.journey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TrustedContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('relationship', models.CharField(blank=True, max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.AddField(
            model_name='journey',
            name='shared_contacts',
            field=models.ManyToManyField(blank=True, related_name='shared_journeys', to='core.trustedcontact'),
        ),
        migrations.CreateModel(
            name='EmergencyContactNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('app', 'App')], max_length=10)),
                ('delivered', models.BooleanField(default=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.emergencyalert')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trustedcontact')),
            ],
        ),
    ]
